/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createLocationSchemaType {
  area?: number;
  name: string;
  number: string;
}

export interface updateLocationSchemaType {
  area?: number;
  name: string;
  number: string;
}
